language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - npm prune
script:
  - npm run build
  - npm run coverage
after_success:
  - npm run docs
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
